In [1]:
import numpy as np

In [36]:
#creating an array 

arr=np.array([1,2,3,4])

In [22]:
arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [15]:
#datatype of an array 

arr=np.array([],dtype='S')

In [35]:
arr=arr.astype(int)

In [12]:
arr

array([1., 2., 3., 4.])

In [20]:
arr=np.arange(10,40,2)

In [21]:
arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [26]:
np.insert(arr,5,int(40))

array([10, 12, 14, 16, 18, 40, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [24]:
np.delete(arr,5)

array([10, 12, 14, 16, 18, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [30]:
arr=np.insert(arr,0,100)

In [31]:
arr

array([100,  10,  12,  14,  16,  18,  20,  22,  24,  26,  28,  30,  32,
        34,  36,  38])

In [38]:
arr=np.append(arr,50)
arr

array([ 1,  2,  3,  4, 50])

In [39]:
arr[3]

4

In [41]:
print(arr)

[ 1  2  3  4 50]


In [37]:
#matrices

In [42]:
mat=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [43]:
print(mat)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [44]:
#speed list
a=[i for i in range(10000000)]
b=[i for i in range(10000000,20000000)]
c=[]
import time as t 
start=time.time()
for i in range(len(a)):
    c.append(a[i]+b[i])
print(time.time()-start)

6.292800426483154


In [48]:
arr1=np.arange(10000000)
arr2=np.arange(10000000,20000000)
import time 
start=time.time()
arr3=arr1+arr2
print(time.time()-start)

0.029776334762573242


In [49]:
6.2/0.02

310.0

In [50]:
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [52]:
mat[1,1]

6

In [54]:
for i in range(3):
    print(mat[i,1])

2
6
10


In [56]:
d3=np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])

In [60]:
d3[1,0,2]

11